version: 2.1
jobs:
  build:
    docker:
      - image: alpine:3.15
    steps:
      - run:
        name: Demo Fist Step
        command: |
          echo 'Hello Neph'
          echo 'Fist delivery pipeline'