version: 2.1
jobs:
  build:
    docker:
      - image: alpine:3.15
    steps:
      - run:
          name: The Fist Step
          command: |
            echo 'Configuration Introduction'
            echo 'Part 1: Using the shell'